//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarchOfTheRays.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarchOfTheRays.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the file?.
        /// </summary>
        internal static string AskSaveChanges {
            get {
                return ResourceManager.GetString("AskSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operation.
        /// </summary>
        internal static string BinaryOperation {
            get {
                return ResourceManager.GetString("BinaryOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        internal static string CameraPosition {
            get {
                return ResourceManager.GetString("CameraPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera settings.
        /// </summary>
        internal static string CameraSettings {
            get {
                return ResourceManager.GetString("CameraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target:.
        /// </summary>
        internal static string CameraTarget {
            get {
                return ResourceManager.GetString("CameraTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up direction:.
        /// </summary>
        internal static string CameraUpDirection {
            get {
                return ResourceManager.GetString("CameraUpDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while opening file.
        /// </summary>
        internal static string CannotOpenFileCaption {
            get {
                return ResourceManager.GetString("CannotOpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while opening {0}.
        /// </summary>
        internal static string CannotOpenFileText {
            get {
                return ResourceManager.GetString("CannotOpenFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while writing file.
        /// </summary>
        internal static string CannotWriteFileCaption {
            get {
                return ResourceManager.GetString("CannotWriteFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing {0}.
        /// </summary>
        internal static string CannotWriteFileText {
            get {
                return ResourceManager.GetString("CannotWriteFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom node.
        /// </summary>
        internal static string CustomNode {
            get {
                return ResourceManager.GetString("CustomNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;ut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Deselect.
        /// </summary>
        internal static string Deselect {
            get {
                return ResourceManager.GetString("Deselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export node.
        /// </summary>
        internal static string ExportNode {
            get {
                return ResourceManager.GetString("ExportNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expressions.
        /// </summary>
        internal static string Expressions {
            get {
                return ResourceManager.GetString("Expressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fit to screen.
        /// </summary>
        internal static string FitToScreen {
            get {
                return ResourceManager.GetString("FitToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to &amp;selection.
        /// </summary>
        internal static string FitToSelection {
            get {
                return ResourceManager.GetString("FitToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D vector constant.
        /// </summary>
        internal static string Float2Constant {
            get {
                return ResourceManager.GetString("Float2Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D vector constant.
        /// </summary>
        internal static string Float3Constant {
            get {
                return ResourceManager.GetString("Float3Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D vector constructor.
        /// </summary>
        internal static string Float3Constructor {
            get {
                return ResourceManager.GetString("Float3Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4D vector constant.
        /// </summary>
        internal static string Float4Constant {
            get {
                return ResourceManager.GetString("Float4Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar constant.
        /// </summary>
        internal static string FloatConstant {
            get {
                return ResourceManager.GetString("FloatConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpPanel {
            get {
                return ResourceManager.GetString("HelpPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import node.
        /// </summary>
        internal static string ImportNode {
            get {
                return ResourceManager.GetString("ImportNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom binary operation.
        /// </summary>
        internal static string InsertCustomBinaryNode {
            get {
                return ResourceManager.GetString("InsertCustomBinaryNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom unary operation.
        /// </summary>
        internal static string InsertCustomNode {
            get {
                return ResourceManager.GetString("InsertCustomNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersection.
        /// </summary>
        internal static string Intersection {
            get {
                return ResourceManager.GetString("Intersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Live preview.
        /// </summary>
        internal static string LivePreview {
            get {
                return ResourceManager.GetString("LivePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main graph.
        /// </summary>
        internal static string MainGraph {
            get {
                return ResourceManager.GetString("MainGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of iterations:.
        /// </summary>
        internal static string MaxIterations {
            get {
                return ResourceManager.GetString("MaxIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum rendering distance.
        /// </summary>
        internal static string MaxRenderDist {
            get {
                return ResourceManager.GetString("MaxRenderDist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March of the Rays file.
        /// </summary>
        internal static string MtrFile {
            get {
                return ResourceManager.GetString("MtrFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string NewDocument {
            get {
                return ResourceManager.GetString("NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March of the Rays node.
        /// </summary>
        internal static string NodeFile {
            get {
                return ResourceManager.GetString("NodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numeric value.
        /// </summary>
        internal static string NumberInputInvalid {
            get {
                return ResourceManager.GetString("NumberInputInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string OpenDocument {
            get {
                return ResourceManager.GetString("OpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Panels.
        /// </summary>
        internal static string Panels {
            get {
                return ResourceManager.GetString("Panels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG.
        /// </summary>
        internal static string PngImage {
            get {
                return ResourceManager.GetString("PngImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewFormTitle {
            get {
                return ResourceManager.GetString("PreviewFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometric primitives.
        /// </summary>
        internal static string Primitives {
            get {
                return ResourceManager.GetString("Primitives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesPanel {
            get {
                return ResourceManager.GetString("PropertiesPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering engine settings.
        /// </summary>
        internal static string RenderingEngineSettings {
            get {
                return ResourceManager.GetString("RenderingEngineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epsilon:.
        /// </summary>
        internal static string RenderingEpsilon {
            get {
                return ResourceManager.GetString("RenderingEpsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rendering.
        /// </summary>
        internal static string RenderingMenu {
            get {
                return ResourceManager.GetString("RenderingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Render preview.
        /// </summary>
        internal static string RenderPreview {
            get {
                return ResourceManager.GetString("RenderPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string RenderSettings {
            get {
                return ResourceManager.GetString("RenderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering settings.
        /// </summary>
        internal static string RenderSettingsTitle {
            get {
                return ResourceManager.GetString("RenderSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset zoom.
        /// </summary>
        internal static string ResetZoom {
            get {
                return ResourceManager.GetString("ResetZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string SaveDocument {
            get {
                return ResourceManager.GetString("SaveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;as....
        /// </summary>
        internal static string SaveDocumentAs {
            get {
                return ResourceManager.GetString("SaveDocumentAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image.
        /// </summary>
        internal static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &amp;all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;help panel.
        /// </summary>
        internal static string ShowHelpPanel {
            get {
                return ResourceManager.GetString("ShowHelpPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show main graph.
        /// </summary>
        internal static string ShowMainGraph {
            get {
                return ResourceManager.GetString("ShowMainGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;preview window.
        /// </summary>
        internal static string ShowPreviewWindow {
            get {
                return ResourceManager.GetString("ShowPreviewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show p&amp;roperties panel.
        /// </summary>
        internal static string ShowPropertiesPanel {
            get {
                return ResourceManager.GetString("ShowPropertiesPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid operations.
        /// </summary>
        internal static string SolidOperations {
            get {
                return ResourceManager.GetString("SolidOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        internal static string Sphere {
            get {
                return ResourceManager.GetString("Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cycle was found in the graph..
        /// </summary>
        internal static string StatusCycleFound {
            get {
                return ResourceManager.GetString("StatusCycleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid node was found in the graph..
        /// </summary>
        internal static string StatusInvalidNode {
            get {
                return ResourceManager.GetString("StatusInvalidNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering in progress....
        /// </summary>
        internal static string StatusRendering {
            get {
                return ResourceManager.GetString("StatusRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for cycles in the graph....
        /// </summary>
        internal static string StatusSearchingCycles {
            get {
                return ResourceManager.GetString("StatusSearchingCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step size:.
        /// </summary>
        internal static string StepSize {
            get {
                return ResourceManager.GetString("StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        internal static string Subtraction {
            get {
                return ResourceManager.GetString("Subtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swizzle.
        /// </summary>
        internal static string Swizzle {
            get {
                return ResourceManager.GetString("Swizzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unary operation.
        /// </summary>
        internal static string UnaryOperation {
            get {
                return ResourceManager.GetString("UnaryOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Union.
        /// </summary>
        internal static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;in.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom &amp;out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
