// This file was automatically generated by SwizzleGen.fsx, do not edit manually
using System.Numerics;
namespace MarchOfTheRays.Core
{
    public static class Swizzle
    {
        public static Vector2 XX(Vector2 arg)
        {
            return new Vector2(arg.X, arg.X);
        }
        
        public static Vector2 XY(Vector2 arg)
        {
            return new Vector2(arg.X, arg.Y);
        }
        
        public static Vector2 YX(Vector2 arg)
        {
            return new Vector2(arg.Y, arg.X);
        }
        
        public static Vector2 YY(Vector2 arg)
        {
            return new Vector2(arg.Y, arg.Y);
        }
        
        public static Vector3 XXX(Vector2 arg)
        {
            return new Vector3(arg.X, arg.X, arg.X);
        }
        
        public static Vector3 XXY(Vector2 arg)
        {
            return new Vector3(arg.X, arg.X, arg.Y);
        }
        
        public static Vector3 XYX(Vector2 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.X);
        }
        
        public static Vector3 XYY(Vector2 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.Y);
        }
        
        public static Vector3 YXX(Vector2 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.X);
        }
        
        public static Vector3 YXY(Vector2 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.Y);
        }
        
        public static Vector3 YYX(Vector2 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.X);
        }
        
        public static Vector3 YYY(Vector2 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 XXXX(Vector2 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 XXXY(Vector2 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 XXYX(Vector2 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 XXYY(Vector2 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 XYXX(Vector2 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 XYXY(Vector2 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 XYYX(Vector2 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 XYYY(Vector2 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 YXXX(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 YXXY(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 YXYX(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 YXYY(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 YYXX(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 YYXY(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 YYYX(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 YYYY(Vector2 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector2 XX(Vector3 arg)
        {
            return new Vector2(arg.X, arg.X);
        }
        
        public static Vector2 XY(Vector3 arg)
        {
            return new Vector2(arg.X, arg.Y);
        }
        
        public static Vector2 XZ(Vector3 arg)
        {
            return new Vector2(arg.X, arg.Z);
        }
        
        public static Vector2 YX(Vector3 arg)
        {
            return new Vector2(arg.Y, arg.X);
        }
        
        public static Vector2 YY(Vector3 arg)
        {
            return new Vector2(arg.Y, arg.Y);
        }
        
        public static Vector2 YZ(Vector3 arg)
        {
            return new Vector2(arg.Y, arg.Z);
        }
        
        public static Vector2 ZX(Vector3 arg)
        {
            return new Vector2(arg.Z, arg.X);
        }
        
        public static Vector2 ZY(Vector3 arg)
        {
            return new Vector2(arg.Z, arg.Y);
        }
        
        public static Vector2 ZZ(Vector3 arg)
        {
            return new Vector2(arg.Z, arg.Z);
        }
        
        public static Vector3 XXX(Vector3 arg)
        {
            return new Vector3(arg.X, arg.X, arg.X);
        }
        
        public static Vector3 XXY(Vector3 arg)
        {
            return new Vector3(arg.X, arg.X, arg.Y);
        }
        
        public static Vector3 XXZ(Vector3 arg)
        {
            return new Vector3(arg.X, arg.X, arg.Z);
        }
        
        public static Vector3 XYX(Vector3 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.X);
        }
        
        public static Vector3 XYY(Vector3 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.Y);
        }
        
        public static Vector3 XYZ(Vector3 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.Z);
        }
        
        public static Vector3 XZX(Vector3 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.X);
        }
        
        public static Vector3 XZY(Vector3 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.Y);
        }
        
        public static Vector3 XZZ(Vector3 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.Z);
        }
        
        public static Vector3 YXX(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.X);
        }
        
        public static Vector3 YXY(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.Y);
        }
        
        public static Vector3 YXZ(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.Z);
        }
        
        public static Vector3 YYX(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.X);
        }
        
        public static Vector3 YYY(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector3 YYZ(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector3 YZX(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.X);
        }
        
        public static Vector3 YZY(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector3 YZZ(Vector3 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector3 ZXX(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.X);
        }
        
        public static Vector3 ZXY(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.Y);
        }
        
        public static Vector3 ZXZ(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.Z);
        }
        
        public static Vector3 ZYX(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.X);
        }
        
        public static Vector3 ZYY(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector3 ZYZ(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector3 ZZX(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.X);
        }
        
        public static Vector3 ZZY(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector3 ZZZ(Vector3 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 XXXX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 XXXY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 XXXZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 XXYX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 XXYY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 XXYZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 XXZX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 XXZY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 XXZZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 XYXX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 XYXY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 XYXZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 XYYX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 XYYY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 XYYZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 XYZX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 XYZY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 XYZZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 XZXX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 XZXY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 XZXZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 XZYX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 XZYY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 XZYZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 XZZX(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 XZZY(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 XZZZ(Vector3 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 YXXX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 YXXY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 YXXZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 YXYX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 YXYY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 YXYZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 YXZX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 YXZY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 YXZZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 YYXX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 YYXY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 YYXZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 YYYX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 YYYY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 YYYZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 YYZX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 YYZY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 YYZZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 YZXX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 YZXY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 YZXZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 YZYX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 YZYY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 YZYZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 YZZX(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 YZZY(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 YZZZ(Vector3 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 ZXXX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 ZXXY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 ZXXZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 ZXYX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 ZXYY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 ZXYZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 ZXZX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 ZXZY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 ZXZZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 ZYXX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 ZYXY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 ZYXZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 ZYYX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 ZYYY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 ZYYZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 ZYZX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 ZYZY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 ZYZZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 ZZXX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 ZZXY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 ZZXZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 ZZYX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 ZZYY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 ZZYZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 ZZZX(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 ZZZY(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 ZZZZ(Vector3 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector2 XX(Vector4 arg)
        {
            return new Vector2(arg.X, arg.X);
        }
        
        public static Vector2 XY(Vector4 arg)
        {
            return new Vector2(arg.X, arg.Y);
        }
        
        public static Vector2 XZ(Vector4 arg)
        {
            return new Vector2(arg.X, arg.Z);
        }
        
        public static Vector2 XW(Vector4 arg)
        {
            return new Vector2(arg.X, arg.W);
        }
        
        public static Vector2 YX(Vector4 arg)
        {
            return new Vector2(arg.Y, arg.X);
        }
        
        public static Vector2 YY(Vector4 arg)
        {
            return new Vector2(arg.Y, arg.Y);
        }
        
        public static Vector2 YZ(Vector4 arg)
        {
            return new Vector2(arg.Y, arg.Z);
        }
        
        public static Vector2 YW(Vector4 arg)
        {
            return new Vector2(arg.Y, arg.W);
        }
        
        public static Vector2 ZX(Vector4 arg)
        {
            return new Vector2(arg.Z, arg.X);
        }
        
        public static Vector2 ZY(Vector4 arg)
        {
            return new Vector2(arg.Z, arg.Y);
        }
        
        public static Vector2 ZZ(Vector4 arg)
        {
            return new Vector2(arg.Z, arg.Z);
        }
        
        public static Vector2 ZW(Vector4 arg)
        {
            return new Vector2(arg.Z, arg.W);
        }
        
        public static Vector2 WX(Vector4 arg)
        {
            return new Vector2(arg.W, arg.X);
        }
        
        public static Vector2 WY(Vector4 arg)
        {
            return new Vector2(arg.W, arg.Y);
        }
        
        public static Vector2 WZ(Vector4 arg)
        {
            return new Vector2(arg.W, arg.Z);
        }
        
        public static Vector2 WW(Vector4 arg)
        {
            return new Vector2(arg.W, arg.W);
        }
        
        public static Vector3 XXX(Vector4 arg)
        {
            return new Vector3(arg.X, arg.X, arg.X);
        }
        
        public static Vector3 XXY(Vector4 arg)
        {
            return new Vector3(arg.X, arg.X, arg.Y);
        }
        
        public static Vector3 XXZ(Vector4 arg)
        {
            return new Vector3(arg.X, arg.X, arg.Z);
        }
        
        public static Vector3 XXW(Vector4 arg)
        {
            return new Vector3(arg.X, arg.X, arg.W);
        }
        
        public static Vector3 XYX(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.X);
        }
        
        public static Vector3 XYY(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.Y);
        }
        
        public static Vector3 XYZ(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.Z);
        }
        
        public static Vector3 XYW(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Y, arg.W);
        }
        
        public static Vector3 XZX(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.X);
        }
        
        public static Vector3 XZY(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.Y);
        }
        
        public static Vector3 XZZ(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.Z);
        }
        
        public static Vector3 XZW(Vector4 arg)
        {
            return new Vector3(arg.X, arg.Z, arg.W);
        }
        
        public static Vector3 XWX(Vector4 arg)
        {
            return new Vector3(arg.X, arg.W, arg.X);
        }
        
        public static Vector3 XWY(Vector4 arg)
        {
            return new Vector3(arg.X, arg.W, arg.Y);
        }
        
        public static Vector3 XWZ(Vector4 arg)
        {
            return new Vector3(arg.X, arg.W, arg.Z);
        }
        
        public static Vector3 XWW(Vector4 arg)
        {
            return new Vector3(arg.X, arg.W, arg.W);
        }
        
        public static Vector3 YXX(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.X);
        }
        
        public static Vector3 YXY(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.Y);
        }
        
        public static Vector3 YXZ(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.Z);
        }
        
        public static Vector3 YXW(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.X, arg.W);
        }
        
        public static Vector3 YYX(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.X);
        }
        
        public static Vector3 YYY(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector3 YYZ(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector3 YYW(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Y, arg.W);
        }
        
        public static Vector3 YZX(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.X);
        }
        
        public static Vector3 YZY(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector3 YZZ(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector3 YZW(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.Z, arg.W);
        }
        
        public static Vector3 YWX(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.W, arg.X);
        }
        
        public static Vector3 YWY(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.W, arg.Y);
        }
        
        public static Vector3 YWZ(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.W, arg.Z);
        }
        
        public static Vector3 YWW(Vector4 arg)
        {
            return new Vector3(arg.Y, arg.W, arg.W);
        }
        
        public static Vector3 ZXX(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.X);
        }
        
        public static Vector3 ZXY(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.Y);
        }
        
        public static Vector3 ZXZ(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.Z);
        }
        
        public static Vector3 ZXW(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.X, arg.W);
        }
        
        public static Vector3 ZYX(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.X);
        }
        
        public static Vector3 ZYY(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector3 ZYZ(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector3 ZYW(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Y, arg.W);
        }
        
        public static Vector3 ZZX(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.X);
        }
        
        public static Vector3 ZZY(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector3 ZZZ(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector3 ZZW(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.Z, arg.W);
        }
        
        public static Vector3 ZWX(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.W, arg.X);
        }
        
        public static Vector3 ZWY(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.W, arg.Y);
        }
        
        public static Vector3 ZWZ(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.W, arg.Z);
        }
        
        public static Vector3 ZWW(Vector4 arg)
        {
            return new Vector3(arg.Z, arg.W, arg.W);
        }
        
        public static Vector3 WXX(Vector4 arg)
        {
            return new Vector3(arg.W, arg.X, arg.X);
        }
        
        public static Vector3 WXY(Vector4 arg)
        {
            return new Vector3(arg.W, arg.X, arg.Y);
        }
        
        public static Vector3 WXZ(Vector4 arg)
        {
            return new Vector3(arg.W, arg.X, arg.Z);
        }
        
        public static Vector3 WXW(Vector4 arg)
        {
            return new Vector3(arg.W, arg.X, arg.W);
        }
        
        public static Vector3 WYX(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Y, arg.X);
        }
        
        public static Vector3 WYY(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Y, arg.Y);
        }
        
        public static Vector3 WYZ(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Y, arg.Z);
        }
        
        public static Vector3 WYW(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Y, arg.W);
        }
        
        public static Vector3 WZX(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Z, arg.X);
        }
        
        public static Vector3 WZY(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Z, arg.Y);
        }
        
        public static Vector3 WZZ(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Z, arg.Z);
        }
        
        public static Vector3 WZW(Vector4 arg)
        {
            return new Vector3(arg.W, arg.Z, arg.W);
        }
        
        public static Vector3 WWX(Vector4 arg)
        {
            return new Vector3(arg.W, arg.W, arg.X);
        }
        
        public static Vector3 WWY(Vector4 arg)
        {
            return new Vector3(arg.W, arg.W, arg.Y);
        }
        
        public static Vector3 WWZ(Vector4 arg)
        {
            return new Vector3(arg.W, arg.W, arg.Z);
        }
        
        public static Vector3 WWW(Vector4 arg)
        {
            return new Vector3(arg.W, arg.W, arg.W);
        }
        
        public static Vector4 XXXX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 XXXY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 XXXZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 XXXW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.X, arg.W);
        }
        
        public static Vector4 XXYX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 XXYY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 XXYZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 XXYW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Y, arg.W);
        }
        
        public static Vector4 XXZX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 XXZY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 XXZZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 XXZW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.Z, arg.W);
        }
        
        public static Vector4 XXWX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.W, arg.X);
        }
        
        public static Vector4 XXWY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.W, arg.Y);
        }
        
        public static Vector4 XXWZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.W, arg.Z);
        }
        
        public static Vector4 XXWW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.X, arg.W, arg.W);
        }
        
        public static Vector4 XYXX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 XYXY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 XYXZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 XYXW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.X, arg.W);
        }
        
        public static Vector4 XYYX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 XYYY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 XYYZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 XYYW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Y, arg.W);
        }
        
        public static Vector4 XYZX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 XYZY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 XYZZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 XYZW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.Z, arg.W);
        }
        
        public static Vector4 XYWX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.W, arg.X);
        }
        
        public static Vector4 XYWY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.W, arg.Y);
        }
        
        public static Vector4 XYWZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.W, arg.Z);
        }
        
        public static Vector4 XYWW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Y, arg.W, arg.W);
        }
        
        public static Vector4 XZXX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 XZXY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 XZXZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 XZXW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.X, arg.W);
        }
        
        public static Vector4 XZYX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 XZYY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 XZYZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 XZYW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Y, arg.W);
        }
        
        public static Vector4 XZZX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 XZZY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 XZZZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 XZZW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.Z, arg.W);
        }
        
        public static Vector4 XZWX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.W, arg.X);
        }
        
        public static Vector4 XZWY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.W, arg.Y);
        }
        
        public static Vector4 XZWZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.W, arg.Z);
        }
        
        public static Vector4 XZWW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.Z, arg.W, arg.W);
        }
        
        public static Vector4 XWXX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.X, arg.X);
        }
        
        public static Vector4 XWXY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.X, arg.Y);
        }
        
        public static Vector4 XWXZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.X, arg.Z);
        }
        
        public static Vector4 XWXW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.X, arg.W);
        }
        
        public static Vector4 XWYX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Y, arg.X);
        }
        
        public static Vector4 XWYY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Y, arg.Y);
        }
        
        public static Vector4 XWYZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Y, arg.Z);
        }
        
        public static Vector4 XWYW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Y, arg.W);
        }
        
        public static Vector4 XWZX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Z, arg.X);
        }
        
        public static Vector4 XWZY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Z, arg.Y);
        }
        
        public static Vector4 XWZZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Z, arg.Z);
        }
        
        public static Vector4 XWZW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.Z, arg.W);
        }
        
        public static Vector4 XWWX(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.W, arg.X);
        }
        
        public static Vector4 XWWY(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.W, arg.Y);
        }
        
        public static Vector4 XWWZ(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.W, arg.Z);
        }
        
        public static Vector4 XWWW(Vector4 arg)
        {
            return new Vector4(arg.X, arg.W, arg.W, arg.W);
        }
        
        public static Vector4 YXXX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 YXXY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 YXXZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 YXXW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.X, arg.W);
        }
        
        public static Vector4 YXYX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 YXYY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 YXYZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 YXYW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Y, arg.W);
        }
        
        public static Vector4 YXZX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 YXZY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 YXZZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 YXZW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.Z, arg.W);
        }
        
        public static Vector4 YXWX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.W, arg.X);
        }
        
        public static Vector4 YXWY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.W, arg.Y);
        }
        
        public static Vector4 YXWZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.W, arg.Z);
        }
        
        public static Vector4 YXWW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.X, arg.W, arg.W);
        }
        
        public static Vector4 YYXX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 YYXY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 YYXZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 YYXW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.X, arg.W);
        }
        
        public static Vector4 YYYX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 YYYY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 YYYZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 YYYW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Y, arg.W);
        }
        
        public static Vector4 YYZX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 YYZY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 YYZZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 YYZW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.Z, arg.W);
        }
        
        public static Vector4 YYWX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.W, arg.X);
        }
        
        public static Vector4 YYWY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.W, arg.Y);
        }
        
        public static Vector4 YYWZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.W, arg.Z);
        }
        
        public static Vector4 YYWW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Y, arg.W, arg.W);
        }
        
        public static Vector4 YZXX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 YZXY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 YZXZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 YZXW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.X, arg.W);
        }
        
        public static Vector4 YZYX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 YZYY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 YZYZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 YZYW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Y, arg.W);
        }
        
        public static Vector4 YZZX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 YZZY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 YZZZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 YZZW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.Z, arg.W);
        }
        
        public static Vector4 YZWX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.W, arg.X);
        }
        
        public static Vector4 YZWY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.W, arg.Y);
        }
        
        public static Vector4 YZWZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.W, arg.Z);
        }
        
        public static Vector4 YZWW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.Z, arg.W, arg.W);
        }
        
        public static Vector4 YWXX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.X, arg.X);
        }
        
        public static Vector4 YWXY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.X, arg.Y);
        }
        
        public static Vector4 YWXZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.X, arg.Z);
        }
        
        public static Vector4 YWXW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.X, arg.W);
        }
        
        public static Vector4 YWYX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Y, arg.X);
        }
        
        public static Vector4 YWYY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Y, arg.Y);
        }
        
        public static Vector4 YWYZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Y, arg.Z);
        }
        
        public static Vector4 YWYW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Y, arg.W);
        }
        
        public static Vector4 YWZX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Z, arg.X);
        }
        
        public static Vector4 YWZY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Z, arg.Y);
        }
        
        public static Vector4 YWZZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Z, arg.Z);
        }
        
        public static Vector4 YWZW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.Z, arg.W);
        }
        
        public static Vector4 YWWX(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.W, arg.X);
        }
        
        public static Vector4 YWWY(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.W, arg.Y);
        }
        
        public static Vector4 YWWZ(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.W, arg.Z);
        }
        
        public static Vector4 YWWW(Vector4 arg)
        {
            return new Vector4(arg.Y, arg.W, arg.W, arg.W);
        }
        
        public static Vector4 ZXXX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 ZXXY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 ZXXZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 ZXXW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.X, arg.W);
        }
        
        public static Vector4 ZXYX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 ZXYY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 ZXYZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 ZXYW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Y, arg.W);
        }
        
        public static Vector4 ZXZX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 ZXZY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 ZXZZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 ZXZW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.Z, arg.W);
        }
        
        public static Vector4 ZXWX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.W, arg.X);
        }
        
        public static Vector4 ZXWY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.W, arg.Y);
        }
        
        public static Vector4 ZXWZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.W, arg.Z);
        }
        
        public static Vector4 ZXWW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.X, arg.W, arg.W);
        }
        
        public static Vector4 ZYXX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 ZYXY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 ZYXZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 ZYXW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.X, arg.W);
        }
        
        public static Vector4 ZYYX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 ZYYY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 ZYYZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 ZYYW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Y, arg.W);
        }
        
        public static Vector4 ZYZX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 ZYZY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 ZYZZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 ZYZW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.Z, arg.W);
        }
        
        public static Vector4 ZYWX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.W, arg.X);
        }
        
        public static Vector4 ZYWY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.W, arg.Y);
        }
        
        public static Vector4 ZYWZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.W, arg.Z);
        }
        
        public static Vector4 ZYWW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Y, arg.W, arg.W);
        }
        
        public static Vector4 ZZXX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 ZZXY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 ZZXZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 ZZXW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.X, arg.W);
        }
        
        public static Vector4 ZZYX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 ZZYY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 ZZYZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 ZZYW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Y, arg.W);
        }
        
        public static Vector4 ZZZX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 ZZZY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 ZZZZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 ZZZW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.Z, arg.W);
        }
        
        public static Vector4 ZZWX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.W, arg.X);
        }
        
        public static Vector4 ZZWY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.W, arg.Y);
        }
        
        public static Vector4 ZZWZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.W, arg.Z);
        }
        
        public static Vector4 ZZWW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.Z, arg.W, arg.W);
        }
        
        public static Vector4 ZWXX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.X, arg.X);
        }
        
        public static Vector4 ZWXY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.X, arg.Y);
        }
        
        public static Vector4 ZWXZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.X, arg.Z);
        }
        
        public static Vector4 ZWXW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.X, arg.W);
        }
        
        public static Vector4 ZWYX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Y, arg.X);
        }
        
        public static Vector4 ZWYY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Y, arg.Y);
        }
        
        public static Vector4 ZWYZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Y, arg.Z);
        }
        
        public static Vector4 ZWYW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Y, arg.W);
        }
        
        public static Vector4 ZWZX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Z, arg.X);
        }
        
        public static Vector4 ZWZY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Z, arg.Y);
        }
        
        public static Vector4 ZWZZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Z, arg.Z);
        }
        
        public static Vector4 ZWZW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.Z, arg.W);
        }
        
        public static Vector4 ZWWX(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.W, arg.X);
        }
        
        public static Vector4 ZWWY(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.W, arg.Y);
        }
        
        public static Vector4 ZWWZ(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.W, arg.Z);
        }
        
        public static Vector4 ZWWW(Vector4 arg)
        {
            return new Vector4(arg.Z, arg.W, arg.W, arg.W);
        }
        
        public static Vector4 WXXX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.X, arg.X);
        }
        
        public static Vector4 WXXY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.X, arg.Y);
        }
        
        public static Vector4 WXXZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.X, arg.Z);
        }
        
        public static Vector4 WXXW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.X, arg.W);
        }
        
        public static Vector4 WXYX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Y, arg.X);
        }
        
        public static Vector4 WXYY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Y, arg.Y);
        }
        
        public static Vector4 WXYZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Y, arg.Z);
        }
        
        public static Vector4 WXYW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Y, arg.W);
        }
        
        public static Vector4 WXZX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Z, arg.X);
        }
        
        public static Vector4 WXZY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Z, arg.Y);
        }
        
        public static Vector4 WXZZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Z, arg.Z);
        }
        
        public static Vector4 WXZW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.Z, arg.W);
        }
        
        public static Vector4 WXWX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.W, arg.X);
        }
        
        public static Vector4 WXWY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.W, arg.Y);
        }
        
        public static Vector4 WXWZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.W, arg.Z);
        }
        
        public static Vector4 WXWW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.X, arg.W, arg.W);
        }
        
        public static Vector4 WYXX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.X, arg.X);
        }
        
        public static Vector4 WYXY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.X, arg.Y);
        }
        
        public static Vector4 WYXZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.X, arg.Z);
        }
        
        public static Vector4 WYXW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.X, arg.W);
        }
        
        public static Vector4 WYYX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Y, arg.X);
        }
        
        public static Vector4 WYYY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Y, arg.Y);
        }
        
        public static Vector4 WYYZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Y, arg.Z);
        }
        
        public static Vector4 WYYW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Y, arg.W);
        }
        
        public static Vector4 WYZX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Z, arg.X);
        }
        
        public static Vector4 WYZY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Z, arg.Y);
        }
        
        public static Vector4 WYZZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Z, arg.Z);
        }
        
        public static Vector4 WYZW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.Z, arg.W);
        }
        
        public static Vector4 WYWX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.W, arg.X);
        }
        
        public static Vector4 WYWY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.W, arg.Y);
        }
        
        public static Vector4 WYWZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.W, arg.Z);
        }
        
        public static Vector4 WYWW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Y, arg.W, arg.W);
        }
        
        public static Vector4 WZXX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.X, arg.X);
        }
        
        public static Vector4 WZXY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.X, arg.Y);
        }
        
        public static Vector4 WZXZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.X, arg.Z);
        }
        
        public static Vector4 WZXW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.X, arg.W);
        }
        
        public static Vector4 WZYX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Y, arg.X);
        }
        
        public static Vector4 WZYY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Y, arg.Y);
        }
        
        public static Vector4 WZYZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Y, arg.Z);
        }
        
        public static Vector4 WZYW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Y, arg.W);
        }
        
        public static Vector4 WZZX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Z, arg.X);
        }
        
        public static Vector4 WZZY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Z, arg.Y);
        }
        
        public static Vector4 WZZZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Z, arg.Z);
        }
        
        public static Vector4 WZZW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.Z, arg.W);
        }
        
        public static Vector4 WZWX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.W, arg.X);
        }
        
        public static Vector4 WZWY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.W, arg.Y);
        }
        
        public static Vector4 WZWZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.W, arg.Z);
        }
        
        public static Vector4 WZWW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.Z, arg.W, arg.W);
        }
        
        public static Vector4 WWXX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.X, arg.X);
        }
        
        public static Vector4 WWXY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.X, arg.Y);
        }
        
        public static Vector4 WWXZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.X, arg.Z);
        }
        
        public static Vector4 WWXW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.X, arg.W);
        }
        
        public static Vector4 WWYX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Y, arg.X);
        }
        
        public static Vector4 WWYY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Y, arg.Y);
        }
        
        public static Vector4 WWYZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Y, arg.Z);
        }
        
        public static Vector4 WWYW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Y, arg.W);
        }
        
        public static Vector4 WWZX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Z, arg.X);
        }
        
        public static Vector4 WWZY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Z, arg.Y);
        }
        
        public static Vector4 WWZZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Z, arg.Z);
        }
        
        public static Vector4 WWZW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.Z, arg.W);
        }
        
        public static Vector4 WWWX(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.W, arg.X);
        }
        
        public static Vector4 WWWY(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.W, arg.Y);
        }
        
        public static Vector4 WWWZ(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.W, arg.Z);
        }
        
        public static Vector4 WWWW(Vector4 arg)
        {
            return new Vector4(arg.W, arg.W, arg.W, arg.W);
        }
        
    }
    
    public enum SwizzleType
    {
        XX,
        XY,
        XZ,
        XW,
        YX,
        YY,
        YZ,
        YW,
        ZX,
        ZY,
        ZZ,
        ZW,
        WX,
        WY,
        WZ,
        WW,
        XXX,
        XXY,
        XXZ,
        XXW,
        XYX,
        XYY,
        XYZ,
        XYW,
        XZX,
        XZY,
        XZZ,
        XZW,
        XWX,
        XWY,
        XWZ,
        XWW,
        YXX,
        YXY,
        YXZ,
        YXW,
        YYX,
        YYY,
        YYZ,
        YYW,
        YZX,
        YZY,
        YZZ,
        YZW,
        YWX,
        YWY,
        YWZ,
        YWW,
        ZXX,
        ZXY,
        ZXZ,
        ZXW,
        ZYX,
        ZYY,
        ZYZ,
        ZYW,
        ZZX,
        ZZY,
        ZZZ,
        ZZW,
        ZWX,
        ZWY,
        ZWZ,
        ZWW,
        WXX,
        WXY,
        WXZ,
        WXW,
        WYX,
        WYY,
        WYZ,
        WYW,
        WZX,
        WZY,
        WZZ,
        WZW,
        WWX,
        WWY,
        WWZ,
        WWW,
        XXXX,
        XXXY,
        XXXZ,
        XXXW,
        XXYX,
        XXYY,
        XXYZ,
        XXYW,
        XXZX,
        XXZY,
        XXZZ,
        XXZW,
        XXWX,
        XXWY,
        XXWZ,
        XXWW,
        XYXX,
        XYXY,
        XYXZ,
        XYXW,
        XYYX,
        XYYY,
        XYYZ,
        XYYW,
        XYZX,
        XYZY,
        XYZZ,
        XYZW,
        XYWX,
        XYWY,
        XYWZ,
        XYWW,
        XZXX,
        XZXY,
        XZXZ,
        XZXW,
        XZYX,
        XZYY,
        XZYZ,
        XZYW,
        XZZX,
        XZZY,
        XZZZ,
        XZZW,
        XZWX,
        XZWY,
        XZWZ,
        XZWW,
        XWXX,
        XWXY,
        XWXZ,
        XWXW,
        XWYX,
        XWYY,
        XWYZ,
        XWYW,
        XWZX,
        XWZY,
        XWZZ,
        XWZW,
        XWWX,
        XWWY,
        XWWZ,
        XWWW,
        YXXX,
        YXXY,
        YXXZ,
        YXXW,
        YXYX,
        YXYY,
        YXYZ,
        YXYW,
        YXZX,
        YXZY,
        YXZZ,
        YXZW,
        YXWX,
        YXWY,
        YXWZ,
        YXWW,
        YYXX,
        YYXY,
        YYXZ,
        YYXW,
        YYYX,
        YYYY,
        YYYZ,
        YYYW,
        YYZX,
        YYZY,
        YYZZ,
        YYZW,
        YYWX,
        YYWY,
        YYWZ,
        YYWW,
        YZXX,
        YZXY,
        YZXZ,
        YZXW,
        YZYX,
        YZYY,
        YZYZ,
        YZYW,
        YZZX,
        YZZY,
        YZZZ,
        YZZW,
        YZWX,
        YZWY,
        YZWZ,
        YZWW,
        YWXX,
        YWXY,
        YWXZ,
        YWXW,
        YWYX,
        YWYY,
        YWYZ,
        YWYW,
        YWZX,
        YWZY,
        YWZZ,
        YWZW,
        YWWX,
        YWWY,
        YWWZ,
        YWWW,
        ZXXX,
        ZXXY,
        ZXXZ,
        ZXXW,
        ZXYX,
        ZXYY,
        ZXYZ,
        ZXYW,
        ZXZX,
        ZXZY,
        ZXZZ,
        ZXZW,
        ZXWX,
        ZXWY,
        ZXWZ,
        ZXWW,
        ZYXX,
        ZYXY,
        ZYXZ,
        ZYXW,
        ZYYX,
        ZYYY,
        ZYYZ,
        ZYYW,
        ZYZX,
        ZYZY,
        ZYZZ,
        ZYZW,
        ZYWX,
        ZYWY,
        ZYWZ,
        ZYWW,
        ZZXX,
        ZZXY,
        ZZXZ,
        ZZXW,
        ZZYX,
        ZZYY,
        ZZYZ,
        ZZYW,
        ZZZX,
        ZZZY,
        ZZZZ,
        ZZZW,
        ZZWX,
        ZZWY,
        ZZWZ,
        ZZWW,
        ZWXX,
        ZWXY,
        ZWXZ,
        ZWXW,
        ZWYX,
        ZWYY,
        ZWYZ,
        ZWYW,
        ZWZX,
        ZWZY,
        ZWZZ,
        ZWZW,
        ZWWX,
        ZWWY,
        ZWWZ,
        ZWWW,
        WXXX,
        WXXY,
        WXXZ,
        WXXW,
        WXYX,
        WXYY,
        WXYZ,
        WXYW,
        WXZX,
        WXZY,
        WXZZ,
        WXZW,
        WXWX,
        WXWY,
        WXWZ,
        WXWW,
        WYXX,
        WYXY,
        WYXZ,
        WYXW,
        WYYX,
        WYYY,
        WYYZ,
        WYYW,
        WYZX,
        WYZY,
        WYZZ,
        WYZW,
        WYWX,
        WYWY,
        WYWZ,
        WYWW,
        WZXX,
        WZXY,
        WZXZ,
        WZXW,
        WZYX,
        WZYY,
        WZYZ,
        WZYW,
        WZZX,
        WZZY,
        WZZZ,
        WZZW,
        WZWX,
        WZWY,
        WZWZ,
        WZWW,
        WWXX,
        WWXY,
        WWXZ,
        WWXW,
        WWYX,
        WWYY,
        WWYZ,
        WWYW,
        WWZX,
        WWZY,
        WWZZ,
        WWZW,
        WWWX,
        WWWY,
        WWWZ,
        WWWW,
    }
    
}

